"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import version

APP = ['P2PP.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    name='p2pp',
    version="{}.{:2}.{:3}".format(version.MajorVersion, version.MinorVersion, version.Build),
    packages=['p2pp'],
    url='https://github.com/tomvandeneede/p2pp',
    license='GPLv3',
    author='tomvandeneede/timbrookman',
    author_email='t.vandeneede@pandora.be',
    description='Prusa Slicer 2 Palette Processor'
)
